version: '3.7'

services:
  # Postgres 11
  db:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
  backend_service:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile_BE
    volumes:
      - ./:/code
    environment:
      - PWPWORKERS=4
    command: >
      bash -c "python wait_for_postgres.py && ./serve-uvicorn-starlette.sh"
    ports:
      - "8000:8000"
    links:
      - db
    restart: always
  frontend_service:
    depends_on:
      - backend_service
    build:
      context: .
      dockerfile: Dockerfile_FE
    volumes:
      - ./:/code
    environment:
      - PWPWORKERS=4
    links:
      - backend_service
    command: >
      bash -c "
      while ! nc -z backend_service 8000;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;

      ./run-benchmark.sh"

