version: '3.7'

services:
  # Postgres 11
  db:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile_BE
    volumes:
      - ./:/code
    environment:
      - PWPWORKERS=4
    command: >
      bash -c "./serve-uvicorn-starlette.sh"
    ports:
      - "8000:8000"
    restart: always
  frontend_service:
    depends_on:
      - backend_service
    build:
      context: .
      dockerfile: Dockerfile_FE
    volumes:
      - ./:/code
    environment:
      - PWPWORKERS=4
    links:
      - backend_service
    command: >
      bash -c "ab -c 1 -n 100 http://backend_service:8000/test && tail -f /dev/null"
    restart: always