version: '3.7'

services:
  # Postgres 11
  db:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500MB
  backend_service:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile_BE
    volumes:
      - ./:/code
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2GB
    environment:
      - PWPWORKERS=1
    command: >

      bash -c "
      while ! nc -z external_service 8001;
        do
          echo sleeping;
          sleep 1;
        done;
      python wait_for_postgres.py && ./serve-uvicorn-quart.sh"
    ports:
      - "8000:8000"
    links:
      - db
      - external_service
    restart: always
    logging:
      driver: none
  frontend_service:
    depends_on:
      - backend_service
    build:
      context: .
      dockerfile: Dockerfile_FE
    volumes:
      - ./:/code
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200MB
    links:
      - backend_service
    command: >
      bash -c "
      while ! nc -z backend_service 8000;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;

      ./run-external-benchmark.sh"
  external_service:
    build:
      context: .
      dockerfile: Dockerfile_ES
    volumes:
      - ./:/code
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB
    command: >
      bash -c "./serve-external-gunicorn-flask.sh"
    ports:
      - "8001:8001"
    links:
      - db
    restart: always

