# Dependencies
FROM segment/chamber:2 AS chamber

FROM python:3.7-slim-stretch

RUN apt update && apt-get -y install netcat && apt-get -y install gcc libstdc++  && apt-get autoclean

WORKDIR /code
COPY . /code


RUN pip install -r requirements.txt

EXPOSE 8000

#ENTRYPOINT ["./docker-entrypoint.sh"]

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]